#!/bin/bash
# License: Unspecified

m4_include(lib/common.sh)

. /etc/makepkg.conf

if [ ! -e "$1" ]; then
	error "Package '$1' does not exists!"
	exit 1
fi

msg "Signing package '$1' with key ${GPGKEY}..."
gpg --detach-sign --use-agent -u "${GPGKEY}" "$1"
